apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode yes
    appendonly yes
    logfile /var/log/redis/redis.log
    requirepass redispass